name: Build images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TARGET: nodered/node-red-dev
      NODE_RED_VERSION: unknown
      PLATFORMS: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/s390x,linux/386
    strategy:
      fail-fast: false
      matrix:
        OS:
          - alpine
          # - buster-slim
        NODE_VERSION:
          - 10
          - 12
          - 14
        TAG_SUFFIX:
          - default
          - minimal
    steps:
      - name: Set TARGET environment variable
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "TARGET=nodered/node-red" >> $GITHUB_ENV

      - name: Get Node-Red version
        run: echo "NODE_RED_VERSION=$(jq .dependencies.\"node-red\" package.json | sed -e 's/"//g')" >> $GITHUB_ENV

      - name: Remove linux/386 from Node 14 build
        if: matrix.NODE_VERSION == 14
        run: echo "PLATFORMS={{ env.PLATFORMS }}" | sed -e 's/linux\/386//g' | sed -e 's/,,/,/g' | sed -e 's/,$//g' >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.${{ matrix.OS }}
          platforms: ${{ env.PLATFORMS }}
          pull: true
          push: true
          tags: |
            dennis14e/node-red:latest-${{ matrix.OS }}-${{ matrix.NODE_VERSION }}-${{ matrix.TAG_SUFFIX }}
            dennis14e/node-red:v${{ env.NODE_RED_VERSION }}-${{ matrix.OS }}-${{ matrix.NODE_VERSION }}-${{ matrix.TAG_SUFFIX }}
          build-args: |
            BUILD_SHA=${{ github.sha }}
            BUILD_REF=${{ github.ref }}
            OS=${{ matrix.OS }}
            NODE_VERSION=${{ matrix.NODE_VERSION }}
            NODE_RED_VERSION=v${{ env.NODE_RED_VERSION }}
            TARGET=${{ env.TARGET }}
            TAG_SUFFIX=${{ matrix.TAG_SUFFIX }}
