name: Build images

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    env:
      BUILD_DATE: unknown
      BUILD_VERSION: unknown
      NODE_RED_VERSION: unknown
      DOCKER_REPO: dennis14e/node-red
      DOCKER_TAGS: unknown
      DOCKER_PUSH: false
      TARGET: dennis14e/node-red-dev
      PLATFORMS: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/s390x
      TAG_SUFFIX: default
      LATEST_NODE: 14
    strategy:
      fail-fast: false
      matrix:
        OS:
          - alpine
          - buster
        NODE_VERSION:
          - 10
          - 12
          - 14
        TAG_SUFFIX:
          - default
          - minimal
    steps:
      - name: Set TARGET environment variable
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "TARGET=dennis14e/node-red" >> $GITHUB_ENV

      - name: Set BUILD_DATE environment variable
        run: echo "BUILD_DATE=$(date +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV

      - name: Set BUILD_VERSION environment variable
        run: echo "BUILD_VERSION=${{ github.run_id }}" >> $GITHUB_ENV

      - name: Set TAG_SUFFIX environment variable
        run: |
          TAG_SUFFIX="-${{ matrix.TAG_SUFFIX }}"
          [ "$TAG_SUFFIX" = "-default" ] && TAG_SUFFIX=""
          echo "TAG_SUFFIX=$TAG_SUFFIX" >> $GITHUB_ENV

      - name: Set DOCKER_PUSH if the origin is this repository
        if: github.ref == 'refs/heads/master'
        run: echo "DOCKER_PUSH=true" >> $GITHUB_ENV

      - name: Remove linux/arm/v6 from buster build
        if: matrix.OS == 'buster'
        run: echo "PLATFORMS=${{ env.PLATFORMS }}" | sed -e 's/linux\/arm\/v6//g' | sed -e 's/,,/,/g' | sed -e 's/,$//g' >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Node-RED version
        run: echo "NODE_RED_VERSION=$(jq .dependencies.\"node-red\" package.json | sed -e 's/"//g')" >> $GITHUB_ENV

      - name: Set Docker tags (global)
        run: |
          TAGS=""
          
          # v1.2.3-10-alpine, v1.2.3-10-alpine-minimal, v1.2.3-10-buster, v1.2.3-10-buster-minimal, v1.2.3-12-alpine, [...]
          TAGS="$TAGS,${{ env.DOCKER_REPO }}:v${{ env.NODE_RED_VERSION }}-${{ matrix.NODE_VERSION }}-${{ matrix.OS }}${{ env.TAG_SUFFIX }}"

          # latest-10-alpine, latest-10-alpine-minimal, latest-10-buster, latest-10-buster-minimal, latest-12-alpine, [...]
          TAGS="$TAGS,${{ env.DOCKER_REPO }}:latest-${{ matrix.NODE_VERSION }}-${{ matrix.OS }}${{ env.TAG_SUFFIX }}"

          echo "DOCKER_TAGS=$TAGS" >> $GITHUB_ENV

      - name: Set Docker tags (alpine)
        if: matrix.OS == 'alpine'
        run: |
          TAGS=""
          
          # v1.2.3-10, v1.2.3-10-minimal, v1.2.3-12, [...]
          TAGS="$TAGS,${{ env.DOCKER_REPO }}:v${{ env.NODE_RED_VERSION }}-${{ matrix.NODE_VERSION }}${{ env.TAG_SUFFIX }}"

          # latest-10, latest-10-minimal, latest-12, [...]
          TAGS="$TAGS,${{ env.DOCKER_REPO }}:latest-${{ matrix.NODE_VERSION }}${{ env.TAG_SUFFIX }}"

          # latest
          [ ${{ matrix.NODE_VERSION }} -eq ${{ env.LATEST_NODE }} ] && [ "${{ matrix.TAG_SUFFIX }}" = "default" ] && TAGS="$TAGS,${{ env.DOCKER_REPO }}:latest"

          echo "DOCKER_TAGS=$TAGS" >> $GITHUB_ENV

      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ env.NODE_RED_VERSION }}-${{ matrix.NODE_VERSION }}-${{ matrix.OS }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ env.NODE_RED_VERSION }}-${{ matrix.NODE_VERSION }}-${{ matrix.OS }}-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        if: env.DOCKER_PUSH == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          file: Dockerfile.${{ matrix.OS }}
          platforms: ${{ env.PLATFORMS }}
          pull: true
          push: ${{ env.DOCKER_PUSH }}
          tags: ${{ env.DOCKER_TAGS }}
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_VERSION=${{ env.BUILD_VERSION }}
            BUILD_REF=${{ github.sha }}
            NODE_VERSION=${{ matrix.NODE_VERSION }}
            NODE_RED_VERSION=v${{ env.NODE_RED_VERSION }}
            TARGET=${{ env.TARGET }}
            TAG_SUFFIX=${{ matrix.TAG_SUFFIX }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKER_REPO }}
          readme-filepath: ./docker/description.md
