name: Lint Dockerfiles

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Lint Dockerfiles
      uses: luke142367/Docker-Lint-Action@v1.0.0
      with:
        target: Dockerfile.alpine Dockerfile.buster
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
